#! /usr/local/bin/perl

@targets = ("irix-mips4","irix-mips4-o","irix-mips3","irix-mips3-o","irix-mips2","irix-mips2-o","hpux","hpux-o","aix","aix-o","solaris","solaris-o");

if(!$ARGV[0]){
    print "Usage : addModule module\n";
    exit(1);
}

foreach $key (@targets){
    $dir = "$ENV{\"RADPHI_HOME\"}/build.$key";
    chdir($dir);
    system("pwd");
    foreach $arg (@ARGV){
	system("cvsCheckout $arg");
    }
}
