/*
   endianConverterAuto.c --- endian converter

   this file is automatically generated by @(#)endianStubGen.perl	1.5	Created 10/1/96 22:47:08
*/


#include <stdio.h>

#include <endianConverterAuto.h>


int endian_convertType1_adc_values_t(adc_values_t *dptr,int dlength)
{

   /* (int32 nadc)	 --> (int32|uint32)	(nadc) */
   /* (adc_value_t adc[1])	 --> (adc_value_t|adc_value_t)	(adc)[dptr->nadc] */

   endian_convertType1_uint32((uint32*)&dptr->nadc,sizeof(dptr->nadc));
   endian_convertTypeN_adc_value_t(dptr->adc,dptr->nadc);

   return 0;
}

int endian_convertType1_bgv_clusters_t(bgv_clusters_t *dptr,int dlength)
{

   /* (int32 nClusters)	 --> (int32|uint32)	(nClusters) */
   /* (bgv_cluster_t clusters[1])	 --> (bgv_cluster_t|bgv_cluster_t)	(clusters)[dptr->nClusters] */

   endian_convertType1_uint32((uint32*)&dptr->nClusters,sizeof(dptr->nClusters));
   endian_convertTypeN_bgv_cluster_t(dptr->clusters,dptr->nClusters);

   return 0;
}

int endian_convertType1_bgv_hits_t(bgv_hits_t *dptr,int dlength)
{

   /* (uint32 nhits)	 --> (uint32|uint32)	(nhits) */
   /* (bgv_hit_t hit[1])	 --> (bgv_hit_t|bgv_hit_t)	(hit)[dptr->nhits] */

   endian_convertType1_uint32((uint32*)&dptr->nhits,sizeof(dptr->nhits));
   endian_convertTypeN_bgv_hit_t(dptr->hit,dptr->nhits);

   return 0;
}

int endian_convertType1_bsd_hits_t(bsd_hits_t *dptr,int dlength)
{

   /* (uint32 nhits)	 --> (uint32|uint32)	(nhits) */
   /* (bsd_hit_t hit[1])	 --> (bsd_hit_t|bsd_hit_t)	(hit)[dptr->nhits] */

   endian_convertType1_uint32((uint32*)&dptr->nhits,sizeof(dptr->nhits));
   endian_convertTypeN_bsd_hit_t(dptr->hit,dptr->nhits);

   return 0;
}

int endian_convertType1_bsd_pixels_t(bsd_pixels_t *dptr,int dlength)
{

   /* (uint32 npixels)	 --> (uint32|uint32)	(npixels) */
   /* (bsd_pixel_t pixel[1])	 --> (bsd_pixel_t|bsd_pixel_t)	(pixel)[dptr->npixels] */

   endian_convertType1_uint32((uint32*)&dptr->npixels,sizeof(dptr->npixels));
   endian_convertTypeN_bsd_pixel_t(dptr->pixel,dptr->npixels);

   return 0;
}

int endian_convertType1_cpv_hits_t(cpv_hits_t *dptr,int dlength)
{

   /* (uint32 nhits)	 --> (uint32|uint32)	(nhits) */
   /* (cpv_hit_t hit[1])	 --> (cpv_hit_t|cpv_hit_t)	(hit)[dptr->nhits] */

   endian_convertType1_uint32((uint32*)&dptr->nhits,sizeof(dptr->nhits));
   endian_convertTypeN_cpv_hit_t(dptr->hit,dptr->nhits);

   return 0;
}

int endian_convertType1_esr_nparticle_t(esr_nparticle_t *dptr,int dlength)
{

   /* (vector3_t production)	 --> (vector3_t|vector3_t)	(production) */
   /* (vector4_t beam)	 --> (vector4_t|vector4_t)	(beam) */
   /* (vector4_t miss)	 --> (vector4_t|vector4_t)	(miss) */
   /* (float mass,mmsq)	 --> (float|uint32)	(mass) */
   /* (float mass,mmsq)	 --> (float|uint32)	(mmsq) */
   /* (int nparticles)	 --> (int|uint32)	(nparticles) */
   /* (int ngammas)	 --> (int|uint32)	(ngammas) */
   /* (int npplus)	 --> (int|uint32)	(npplus) */
   /* (int npminus)	 --> (int|uint32)	(npminus) */
   /* (float chsq)	 --> (float|uint32)	(chsq) */
   /* (float cl)	 --> (float|uint32)	(cl) */
   /* (int charge)	 --> (int|uint32)	(charge) */
   /* (esr_particle_t p[1])	 --> (esr_particle_t|esr_particle_t)	(p)[dptr->nparticles] */

   endian_convertType1_vector3_t((vector3_t*)&dptr->production,sizeof(dptr->production));
   endian_convertType1_vector4_t((vector4_t*)&dptr->beam,sizeof(dptr->beam));
   endian_convertType1_vector4_t((vector4_t*)&dptr->miss,sizeof(dptr->miss));
   endian_convertType1_uint32((uint32*)&dptr->mass,sizeof(dptr->mass));
   endian_convertType1_uint32((uint32*)&dptr->mmsq,sizeof(dptr->mmsq));
   endian_convertType1_uint32((uint32*)&dptr->nparticles,sizeof(dptr->nparticles));
   endian_convertType1_uint32((uint32*)&dptr->ngammas,sizeof(dptr->ngammas));
   endian_convertType1_uint32((uint32*)&dptr->npplus,sizeof(dptr->npplus));
   endian_convertType1_uint32((uint32*)&dptr->npminus,sizeof(dptr->npminus));
   endian_convertType1_uint32((uint32*)&dptr->chsq,sizeof(dptr->chsq));
   endian_convertType1_uint32((uint32*)&dptr->cl,sizeof(dptr->cl));
   endian_convertType1_uint32((uint32*)&dptr->charge,sizeof(dptr->charge));
   endian_convertTypeN_esr_particle_t(dptr->p,dptr->nparticles);

   return 0;
}

int endian_convertType1_frozen_groups_t(frozen_groups_t *dptr,int dlength)
{

   /* (int32 nvalues)	 --> (int32|uint32)	(nvalues) */
   /* (uint16 value[1])	 --> (uint16|uint16)	(value)[dptr->nvalues] */

   endian_convertType1_uint32((uint32*)&dptr->nvalues,sizeof(dptr->nvalues));
   endian_convertTypeN_uint16((uint16*)dptr->value,dptr->nvalues);

   return 0;
}

int endian_convertType1_group_header_t(group_header_t *dptr,int dlength)
{

   /* (uint32 length)	 --> (uint32|uint32)	(length) */
   /* (uint32 type)	 --> (uint32|uint32)	(type) */
   /* (uint32 subtype)	 --> (uint32|uint32)	(subtype) */

   endian_convertType1_uint32((uint32*)&dptr->length,sizeof(dptr->length));
   endian_convertType1_uint32((uint32*)&dptr->type,sizeof(dptr->type));
   endian_convertType1_uint32((uint32*)&dptr->subtype,sizeof(dptr->subtype));

   return 0;
}


int endian_convertTypeN_group_header_t(group_header_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_group_header_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_itape_header_t(itape_header_t *dptr,int dlength)
{

   /* (uint32 length)	 --> (uint32|uint32)	(length) */
   /* (uint32 type)	 --> (uint32|uint32)	(type) */
   /* (uint32 transComputerCode)	 --> (uint32|uint32)	(transComputerCode) */
   /* (uint32 ngroups)	 --> (uint32|uint32)	(ngroups) */
   /* (int32 runNo)	 --> (int32|uint32)	(runNo) */
   /* (uint32 spillNo)	 --> (uint32|uint32)	(spillNo) */
   /* (int32 eventNo)	 --> (int32|uint32)	(eventNo) */
   /* (uint16 eventType)	 --> (uint16|uint16)	(eventType) */
   /* (int16 trigger)	 --> (int16|uint16)	(trigger) */
   /* (int32 time)	 --> (int32|uint32)	(time) */
   /* (uint32 latch)	 --> (uint32|uint32)	(latch) */

   endian_convertType1_uint32((uint32*)&dptr->length,sizeof(dptr->length));
   endian_convertType1_uint32((uint32*)&dptr->type,sizeof(dptr->type));
   endian_convertType1_uint32((uint32*)&dptr->transComputerCode,sizeof(dptr->transComputerCode));
   endian_convertType1_uint32((uint32*)&dptr->ngroups,sizeof(dptr->ngroups));
   endian_convertType1_uint32((uint32*)&dptr->runNo,sizeof(dptr->runNo));
   endian_convertType1_uint32((uint32*)&dptr->spillNo,sizeof(dptr->spillNo));
   endian_convertType1_uint32((uint32*)&dptr->eventNo,sizeof(dptr->eventNo));
   endian_convertType1_uint16((uint16*)&dptr->eventType,sizeof(dptr->eventType));
   endian_convertType1_uint16((uint16*)&dptr->trigger,sizeof(dptr->trigger));
   endian_convertType1_uint32((uint32*)&dptr->time,sizeof(dptr->time));
   endian_convertType1_uint32((uint32*)&dptr->latch,sizeof(dptr->latch));

   return 0;
}


int endian_convertTypeN_itape_header_t(itape_header_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_itape_header_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_lgd_clusters_t(lgd_clusters_t *dptr,int dlength)
{

   /* (int nClusters)	 --> (int|uint32)	(nClusters) */
   /* (lgd_cluster_t cluster[1])	 --> (lgd_cluster_t|lgd_cluster_t)	(cluster)[dptr->nClusters] */

   endian_convertType1_uint32((uint32*)&dptr->nClusters,sizeof(dptr->nClusters));
   endian_convertTypeN_lgd_cluster_t(dptr->cluster,dptr->nClusters);

   return 0;
}

int endian_convertType1_lgd_hits_t(lgd_hits_t *dptr,int dlength)
{

   /* (int nhits)	 --> (int|uint32)	(nhits) */
   /* (lgd_hit_t hit[1])	 --> (lgd_hit_t|lgd_hit_t)	(hit)[dptr->nhits] */

   endian_convertType1_uint32((uint32*)&dptr->nhits,sizeof(dptr->nhits));
   endian_convertTypeN_lgd_hit_t(dptr->hit,dptr->nhits);

   return 0;
}

int endian_convertType1_lgd_reconstruct_t(lgd_reconstruct_t *dptr,int dlength)
{

   /* (int nClusters)	 --> (int|uint32)	(nClusters) */
   /* (int split_mult)	 --> (int|uint32)	(split_mult) */
   /* (float next_conf_level)	 --> (float|uint32)	(next_conf_level) */
   /* (lgd_cluster_t cluster[1])	 --> (lgd_cluster_t|lgd_cluster_t)	(cluster)[dptr->next_conf_level] */

   endian_convertType1_uint32((uint32*)&dptr->nClusters,sizeof(dptr->nClusters));
   endian_convertType1_uint32((uint32*)&dptr->split_mult,sizeof(dptr->split_mult));
   endian_convertType1_uint32((uint32*)&dptr->next_conf_level,sizeof(dptr->next_conf_level));
   endian_convertTypeN_lgd_cluster_t(dptr->cluster,dptr->next_conf_level);

   return 0;
}

int endian_convertType1_mc_event_t(mc_event_t *dptr,int dlength)
{

   /* (uint32 npart)	 --> (uint32|uint32)	(npart) */
   /* (int32 type)	 --> (int32|uint32)	(type) */
   /* (float32 weight)	 --> (float32|uint32)	(weight) */
   /* (uint32 nfinalVert)	 --> (uint32|uint32)	(nfinalVert) */
   /* (mc_particle_t part[1])	 --> (mc_particle_t|mc_particle_t)	(part)[dptr->nfinalVert] */

   endian_convertType1_uint32((uint32*)&dptr->npart,sizeof(dptr->npart));
   endian_convertType1_uint32((uint32*)&dptr->type,sizeof(dptr->type));
   endian_convertType1_uint32((uint32*)&dptr->weight,sizeof(dptr->weight));
   endian_convertType1_uint32((uint32*)&dptr->nfinalVert,sizeof(dptr->nfinalVert));
   endian_convertTypeN_mc_particle_t(dptr->part,dptr->nfinalVert);

   return 0;
}

int endian_convertType1_mc_vertex_t(mc_vertex_t *dptr,int dlength)
{

   /* (uint32 npart)	 --> (uint32|uint32)	(npart) */
   /* (uint32 kind)	 --> (uint32|uint32)	(kind) */
   /* (vector4_t origin)	 --> (vector4_t|vector4_t)	(origin) */
   /* (mc_particle_t part[1])	 --> (mc_particle_t|mc_particle_t)	(part)[dptr->npart] */

   endian_convertType1_uint32((uint32*)&dptr->npart,sizeof(dptr->npart));
   endian_convertType1_uint32((uint32*)&dptr->kind,sizeof(dptr->kind));
   endian_convertType1_vector4_t((vector4_t*)&dptr->origin,sizeof(dptr->origin));
   endian_convertTypeN_mc_particle_t(dptr->part,dptr->npart);

   return 0;
}

int endian_convertType1_mesons_t(mesons_t *dptr,int dlength)
{

   /* (int nMesons)	 --> (int|uint32)	(nMesons) */
   /* (meson_t meson[1])	 --> (meson_t|meson_t)	(meson)[dptr->nMesons] */

   endian_convertType1_uint32((uint32*)&dptr->nMesons,sizeof(dptr->nMesons));
   endian_convertTypeN_meson_t(dptr->meson,dptr->nMesons);

   return 0;
}

int endian_convertType1_photons_t(photons_t *dptr,int dlength)
{

   /* (int nPhotons)	 --> (int|uint32)	(nPhotons) */
   /* (photon_t photon[1])	 --> (photon_t|photon_t)	(photon)[dptr->nPhotons] */

   endian_convertType1_uint32((uint32*)&dptr->nPhotons,sizeof(dptr->nPhotons));
   endian_convertTypeN_photon_t(dptr->photon,dptr->nPhotons);

   return 0;
}

int endian_convertType1_recoil_t(recoil_t *dptr,int dlength)
{

   /* (uint32 npixels)	 --> (uint32|uint32)	(npixels) */
   /* (uint32 pixel_index[MAX_PIXELS_IN_RECOIL])	 --> (uint32|uint32)	(pixel_index)[MAX_PIXELS_IN_RECOIL] */
   /* (float theta)	 --> (float|uint32)	(theta) */
   /* (float phi)	 --> (float|uint32)	(phi) */
   /* (float time)	 --> (float|uint32)	(time) */
   /* (float dEdx)	 --> (float|uint32)	(dEdx) */
   /* (float energy)	 --> (float|uint32)	(energy) */

   endian_convertType1_uint32((uint32*)&dptr->npixels,sizeof(dptr->npixels));
   endian_convertTypeN_uint32((uint32*)dptr->pixel_index,MAX_PIXELS_IN_RECOIL);
   endian_convertType1_uint32((uint32*)&dptr->theta,sizeof(dptr->theta));
   endian_convertType1_uint32((uint32*)&dptr->phi,sizeof(dptr->phi));
   endian_convertType1_uint32((uint32*)&dptr->time,sizeof(dptr->time));
   endian_convertType1_uint32((uint32*)&dptr->dEdx,sizeof(dptr->dEdx));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));

   return 0;
}


int endian_convertTypeN_recoil_t(recoil_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_recoil_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_reg_values_t(reg_values_t *dptr,int dlength)
{

   /* (int32 nregs)	 --> (int32|uint32)	(nregs) */
   /* (reg_value_t reg[1])	 --> (reg_value_t|reg_value_t)	(reg)[dptr->nregs] */

   endian_convertType1_uint32((uint32*)&dptr->nregs,sizeof(dptr->nregs));
   endian_convertTypeN_reg_value_t(dptr->reg,dptr->nregs);

   return 0;
}

int endian_convertType1_rpd_coins_t(rpd_coins_t *dptr,int dlength)
{

   /* (uint32 ncoins)	 --> (uint32|uint32)	(ncoins) */
   /* (rpd_coin_t coin[1])	 --> (rpd_coin_t|rpd_coin_t)	(coin)[dptr->ncoins] */

   endian_convertType1_uint32((uint32*)&dptr->ncoins,sizeof(dptr->ncoins));
   endian_convertTypeN_rpd_coin_t(dptr->coin,dptr->ncoins);

   return 0;
}

int endian_convertType1_rpd_hits_t(rpd_hits_t *dptr,int dlength)
{

   /* (uint32 nhits)	 --> (uint32|uint32)	(nhits) */
   /* (rpd_hit_t hit[1])	 --> (rpd_hit_t|rpd_hit_t)	(hit)[dptr->nhits] */

   endian_convertType1_uint32((uint32*)&dptr->nhits,sizeof(dptr->nhits));
   endian_convertTypeN_rpd_hit_t(dptr->hit,dptr->nhits);

   return 0;
}

int endian_convertType1_scaler_values_t(scaler_values_t *dptr,int dlength)
{

   /* (int32 nscalers)	 --> (int32|uint32)	(nscalers) */
   /* (scaler_value_t scaler[1])	 --> (scaler_value_t|scaler_value_t)	(scaler)[dptr->nscalers] */

   endian_convertType1_uint32((uint32*)&dptr->nscalers,sizeof(dptr->nscalers));
   endian_convertTypeN_scaler_value_t(dptr->scaler,dptr->nscalers);

   return 0;
}

int endian_convertType1_tagger_clusters_t(tagger_clusters_t *dptr,int dlength)
{

   /* (int nclusters)	 --> (int|uint32)	(nclusters) */
   /* (tagger_cluster_t cluster[1])	 --> (tagger_cluster_t|tagger_cluster_t)	(cluster)[dptr->nclusters] */

   endian_convertType1_uint32((uint32*)&dptr->nclusters,sizeof(dptr->nclusters));
   endian_convertTypeN_tagger_cluster_t(dptr->cluster,dptr->nclusters);

   return 0;
}

int endian_convertType1_tagger_hits_t(tagger_hits_t *dptr,int dlength)
{

   /* (uint32 nhits)	 --> (uint32|uint32)	(nhits) */
   /* (tagger_hit_t hit[1])	 --> (tagger_hit_t|tagger_hit_t)	(hit)[dptr->nhits] */

   endian_convertType1_uint32((uint32*)&dptr->nhits,sizeof(dptr->nhits));
   endian_convertTypeN_tagger_hit_t(dptr->hit,dptr->nhits);

   return 0;
}

int endian_convertType1_tagger_photons_t(tagger_photons_t *dptr,int dlength)
{

   /* (int nphotons)	 --> (int|uint32)	(nphotons) */
   /* (tagger_photon_t photon[1])	 --> (tagger_photon_t|tagger_photon_t)	(photon)[dptr->nphotons] */

   endian_convertType1_uint32((uint32*)&dptr->nphotons,sizeof(dptr->nphotons));
   endian_convertTypeN_tagger_photon_t(dptr->photon,dptr->nphotons);

   return 0;
}

int endian_convertType1_tapeHeader_t(tapeHeader_t *dptr,int dlength)
{

   /* (uint32 length)	 --> (uint32|uint32)	(length) */
   /* (uint32 type)	 --> (uint32|uint32)	(type) */
   /* (uint32 transComputerCode)	 --> (uint32|uint32)	(transComputerCode) */
   /* (uint32 ngroups)	 --> (uint32|uint32)	(ngroups) */
   /* (uint32 tapeSeqNumber)	 --> (uint32|uint32)	(tapeSeqNumber) */
   /* (uint32 startTime)	 --> (uint32|uint32)	(startTime) */
   /* (char devname[256])	 --> (char|uint8)	(devname)[256] */
   /* (char from[256])	 --> (char|uint8)	(from)[256] */
   /* (char crc[4])	 --> (char|uint8)	(crc)[4] */

   endian_convertType1_uint32((uint32*)&dptr->length,sizeof(dptr->length));
   endian_convertType1_uint32((uint32*)&dptr->type,sizeof(dptr->type));
   endian_convertType1_uint32((uint32*)&dptr->transComputerCode,sizeof(dptr->transComputerCode));
   endian_convertType1_uint32((uint32*)&dptr->ngroups,sizeof(dptr->ngroups));
   endian_convertType1_uint32((uint32*)&dptr->tapeSeqNumber,sizeof(dptr->tapeSeqNumber));
   endian_convertType1_uint32((uint32*)&dptr->startTime,sizeof(dptr->startTime));
   endian_convertTypeN_uint8((uint8*)dptr->devname,256);
   endian_convertTypeN_uint8((uint8*)dptr->from,256);
   endian_convertTypeN_uint8((uint8*)dptr->crc,4);

   return 0;
}


int endian_convertTypeN_tapeHeader_t(tapeHeader_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_tapeHeader_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_tdc_values_t(tdc_values_t *dptr,int dlength)
{

   /* (int32 ntdc)	 --> (int32|uint32)	(ntdc) */
   /* (tdc_value_t tdc[1])	 --> (tdc_value_t|tdc_value_t)	(tdc)[dptr->ntdc] */

   endian_convertType1_uint32((uint32*)&dptr->ntdc,sizeof(dptr->ntdc));
   endian_convertTypeN_tdc_value_t(dptr->tdc,dptr->ntdc);

   return 0;
}

int endian_convertType1_three_photon_fits_t(three_photon_fits_t *dptr,int dlength)
{

   /* (int nfits)	 --> (int|uint32)	(nfits) */
   /* (three_photon_fit_t fit[1])	 --> (three_photon_fit_t|three_photon_fit_t)	(fit)[dptr->nfits] */

   endian_convertType1_uint32((uint32*)&dptr->nfits,sizeof(dptr->nfits));
   endian_convertTypeN_three_photon_fit_t(dptr->fit,dptr->nfits);

   return 0;
}

int endian_convertType1_time_list_t(time_list_t *dptr,int dlength)
{

   /* (uint32 nelements)	 --> (uint32|uint32)	(nelements) */
   /* (time_list_el_t element[1])	 --> (time_list_el_t|time_list_el_t)	(element)[dptr->nelements] */

   endian_convertType1_uint32((uint32*)&dptr->nelements,sizeof(dptr->nelements));
   endian_convertTypeN_time_list_el_t(dptr->element,dptr->nelements);

   return 0;
}

int endian_convertType1_upv_hits_t(upv_hits_t *dptr,int dlength)
{

   /* (uint32 nhits)	 --> (uint32|uint32)	(nhits) */
   /* (upv_hit_t hit[1])	 --> (upv_hit_t|upv_hit_t)	(hit)[dptr->nhits] */

   endian_convertType1_uint32((uint32*)&dptr->nhits,sizeof(dptr->nhits));
   endian_convertTypeN_upv_hit_t(dptr->hit,dptr->nhits);

   return 0;
}

int endian_convertType1_adc_value_t(adc_value_t *dptr,int dlength)
{

   /* (uint16 mam)	 --> (uint16|uint16)	(mam) */
   /* (uint16 dor)	 --> (uint16|uint16)	(dor) */
   /* (uint32 slot)	 --> (uint32|uint32)	(slot) */
   /* (uint32 channel)	 --> (uint32|uint32)	(channel) */
   /* (uint32 value)	 --> (uint32|uint32)	(value) */

   endian_convertType1_uint16((uint16*)&dptr->mam,sizeof(dptr->mam));
   endian_convertType1_uint16((uint16*)&dptr->dor,sizeof(dptr->dor));
   endian_convertType1_uint32((uint32*)&dptr->slot,sizeof(dptr->slot));
   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertType1_uint32((uint32*)&dptr->value,sizeof(dptr->value));

   return 0;
}


int endian_convertTypeN_adc_value_t(adc_value_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_adc_value_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_bgv_cluster_t(bgv_cluster_t *dptr,int dlength)
{

   /* (float32 energy)	 --> (float32|uint32)	(energy) */
   /* (float32 energy_up)	 --> (float32|uint32)	(energy_up) */
   /* (float32 energy_dn)	 --> (float32|uint32)	(energy_dn) */
   /* (float32 phi)	 --> (float32|uint32)	(phi) */
   /* (float32 z)	 --> (float32|uint32)	(z) */
   /* (float32 t)	 --> (float32|uint32)	(t) */
   /* (float32 scintEnergy)	 --> (float32|uint32)	(scintEnergy) */

   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));
   endian_convertType1_uint32((uint32*)&dptr->energy_up,sizeof(dptr->energy_up));
   endian_convertType1_uint32((uint32*)&dptr->energy_dn,sizeof(dptr->energy_dn));
   endian_convertType1_uint32((uint32*)&dptr->phi,sizeof(dptr->phi));
   endian_convertType1_uint32((uint32*)&dptr->z,sizeof(dptr->z));
   endian_convertType1_uint32((uint32*)&dptr->t,sizeof(dptr->t));
   endian_convertType1_uint32((uint32*)&dptr->scintEnergy,sizeof(dptr->scintEnergy));

   return 0;
}


int endian_convertTypeN_bgv_cluster_t(bgv_cluster_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_bgv_cluster_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_bgv_hit_t(bgv_hit_t *dptr,int dlength)
{

   /* (int32 channel)	 --> (int32|uint32)	(channel) */
   /* (float32 energy[2])	 --> (float32|uint32)	(energy)[2] */
   /* (uint16 times[2])	 --> (uint16|uint16)	(times)[2] */
   /* (uint16 tindex[2])	 --> (uint16|uint16)	(tindex)[2] */

   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertTypeN_uint32((uint32*)dptr->energy,2);
   endian_convertTypeN_uint16((uint16*)dptr->times,2);
   endian_convertTypeN_uint16((uint16*)dptr->tindex,2);

   return 0;
}


int endian_convertTypeN_bgv_hit_t(bgv_hit_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_bgv_hit_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_bsd_hit_t(bsd_hit_t *dptr,int dlength)
{

   /* (int32 channel)	 --> (int32|uint32)	(channel) */
   /* (float32 energy)	 --> (float32|uint32)	(energy) */
   /* (uint32 times)	 --> (uint32|uint32)	(times) */
   /* (uint32 tindex)	 --> (uint32|uint32)	(tindex) */

   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));
   endian_convertType1_uint32((uint32*)&dptr->times,sizeof(dptr->times));
   endian_convertType1_uint32((uint32*)&dptr->tindex,sizeof(dptr->tindex));

   return 0;
}


int endian_convertTypeN_bsd_hit_t(bsd_hit_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_bsd_hit_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_bsd_pixel_t(bsd_pixel_t *dptr,int dlength)
{

   /* (uint32 right)	 --> (uint32|uint32)	(right) */
   /* (uint32 left)	 --> (uint32|uint32)	(left) */
   /* (uint32 straight)	 --> (uint32|uint32)	(straight) */
   /* (uint32 ring)	 --> (uint32|uint32)	(ring) */
   /* (float z)	 --> (float|uint32)	(z) */
   /* (float phi)	 --> (float|uint32)	(phi) */
   /* (float energy[3])	 --> (float|uint32)	(energy)[3] */
   /* (float time[3])	 --> (float|uint32)	(time)[3] */

   endian_convertType1_uint32((uint32*)&dptr->right,sizeof(dptr->right));
   endian_convertType1_uint32((uint32*)&dptr->left,sizeof(dptr->left));
   endian_convertType1_uint32((uint32*)&dptr->straight,sizeof(dptr->straight));
   endian_convertType1_uint32((uint32*)&dptr->ring,sizeof(dptr->ring));
   endian_convertType1_uint32((uint32*)&dptr->z,sizeof(dptr->z));
   endian_convertType1_uint32((uint32*)&dptr->phi,sizeof(dptr->phi));
   endian_convertTypeN_uint32((uint32*)dptr->energy,3);
   endian_convertTypeN_uint32((uint32*)dptr->time,3);

   return 0;
}


int endian_convertTypeN_bsd_pixel_t(bsd_pixel_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_bsd_pixel_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_cpv_hit_t(cpv_hit_t *dptr,int dlength)
{

   /* (int32 channel)	 --> (int32|uint32)	(channel) */
   /* (float32 energy)	 --> (float32|uint32)	(energy) */
   /* (uint32 times)	 --> (uint32|uint32)	(times) */
   /* (uint32 tindex)	 --> (uint32|uint32)	(tindex) */

   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));
   endian_convertType1_uint32((uint32*)&dptr->times,sizeof(dptr->times));
   endian_convertType1_uint32((uint32*)&dptr->tindex,sizeof(dptr->tindex));

   return 0;
}


int endian_convertTypeN_cpv_hit_t(cpv_hit_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_cpv_hit_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_esr_particle_t(esr_particle_t *dptr,int dlength)
{

   /* (vector4_t p)	 --> (vector4_t|vector4_t)	(p) */
   /* (int charge)	 --> (int|uint32)	(charge) */
   /* (float xi2)	 --> (float|uint32)	(xi2) */
   /* (int flags)	 --> (int|uint32)	(flags) */
   /* (Particle_t particleType)	 --> (Particle_t|uint32)	(particleType) */
   /* (particleID_t parent,child)	 --> (particleID_t|particleID_t)	(parent) */
   /* (particleID_t parent,child)	 --> (particleID_t|particleID_t)	(child) */

   endian_convertType1_vector4_t((vector4_t*)&dptr->p,sizeof(dptr->p));
   endian_convertType1_uint32((uint32*)&dptr->charge,sizeof(dptr->charge));
   endian_convertType1_uint32((uint32*)&dptr->xi2,sizeof(dptr->xi2));
   endian_convertType1_uint32((uint32*)&dptr->flags,sizeof(dptr->flags));
   endian_convertType1_uint32((uint32*)&dptr->particleType,sizeof(dptr->particleType));
   endian_convertType1_particleID_t(&dptr->parent,sizeof(dptr->parent));
   endian_convertType1_particleID_t(&dptr->child,sizeof(dptr->child));

   return 0;
}


int endian_convertTypeN_esr_particle_t(esr_particle_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_esr_particle_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_lgd_cluster_t(lgd_cluster_t *dptr,int dlength)
{

   /* (int nBlocks)	 --> (int|uint32)	(nBlocks) */
   /* (int firstBlock)	 --> (int|uint32)	(firstBlock) */
   /* (int flags)	 --> (int|uint32)	(flags) */
   /* (vector3_t space)	 --> (vector3_t|vector3_t)	(space) */
   /* (float width)	 --> (float|uint32)	(width) */
   /* (float energy)	 --> (float|uint32)	(energy) */

   endian_convertType1_uint32((uint32*)&dptr->nBlocks,sizeof(dptr->nBlocks));
   endian_convertType1_uint32((uint32*)&dptr->firstBlock,sizeof(dptr->firstBlock));
   endian_convertType1_uint32((uint32*)&dptr->flags,sizeof(dptr->flags));
   endian_convertType1_vector3_t((vector3_t*)&dptr->space,sizeof(dptr->space));
   endian_convertType1_uint32((uint32*)&dptr->width,sizeof(dptr->width));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));

   return 0;
}


int endian_convertTypeN_lgd_cluster_t(lgd_cluster_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_lgd_cluster_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_lgd_hit_t(lgd_hit_t *dptr,int dlength)
{

   /* (int channel)	 --> (int|uint32)	(channel) */
   /* (float energy)	 --> (float|uint32)	(energy) */

   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));

   return 0;
}


int endian_convertTypeN_lgd_hit_t(lgd_hit_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_lgd_hit_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_mc_particle_t(mc_particle_t *dptr,int dlength)
{

   /* (uint32 kind)	 --> (uint32|uint32)	(kind) */
   /* (vector4_t momentum)	 --> (vector4_t|vector4_t)	(momentum) */

   endian_convertType1_uint32((uint32*)&dptr->kind,sizeof(dptr->kind));
   endian_convertType1_vector4_t((vector4_t*)&dptr->momentum,sizeof(dptr->momentum));

   return 0;
}


int endian_convertTypeN_mc_particle_t(mc_particle_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_mc_particle_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_meson_t(meson_t *dptr,int dlength)
{

   /* (Particle_t type)	 --> (Particle_t|uint32)	(type) */
   /* (vector3_t momentum)	 --> (vector3_t|vector3_t)	(momentum) */
   /* (vector3_t vertex)	 --> (vector3_t|vector3_t)	(vertex) */
   /* (float energy)	 --> (float|uint32)	(energy) */
   /* (float mass)	 --> (float|uint32)	(mass) */
   /* (int ndecay)	 --> (int|uint32)	(ndecay) */
   /* (Particle_t dtype[3])	 --> (Particle_t|uint32)	(dtype)[3] */
   /* (int daughter[3])	 --> (int|uint32)	(daughter)[3] */

   endian_convertType1_uint32((uint32*)&dptr->type,sizeof(dptr->type));
   endian_convertType1_vector3_t((vector3_t*)&dptr->momentum,sizeof(dptr->momentum));
   endian_convertType1_vector3_t((vector3_t*)&dptr->vertex,sizeof(dptr->vertex));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));
   endian_convertType1_uint32((uint32*)&dptr->mass,sizeof(dptr->mass));
   endian_convertType1_uint32((uint32*)&dptr->ndecay,sizeof(dptr->ndecay));
   endian_convertTypeN_uint32((uint32*)dptr->dtype,3);
   endian_convertTypeN_uint32((uint32*)dptr->daughter,3);

   return 0;
}


int endian_convertTypeN_meson_t(meson_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_meson_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_photon_t(photon_t *dptr,int dlength)
{

   /* (int cluster)	 --> (int|uint32)	(cluster) */
   /* (vector3_t momentum)	 --> (vector3_t|vector3_t)	(momentum) */
   /* (vector3_t position)	 --> (vector3_t|vector3_t)	(position) */
   /* (float energy)	 --> (float|uint32)	(energy) */

   endian_convertType1_uint32((uint32*)&dptr->cluster,sizeof(dptr->cluster));
   endian_convertType1_vector3_t((vector3_t*)&dptr->momentum,sizeof(dptr->momentum));
   endian_convertType1_vector3_t((vector3_t*)&dptr->position,sizeof(dptr->position));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));

   return 0;
}


int endian_convertTypeN_photon_t(photon_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_photon_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_reg_value_t(reg_value_t *dptr,int dlength)
{

   /* (int32 index)	 --> (int32|uint32)	(index) */
   /* (uint32 contents)	 --> (uint32|uint32)	(contents) */

   endian_convertType1_uint32((uint32*)&dptr->index,sizeof(dptr->index));
   endian_convertType1_uint32((uint32*)&dptr->contents,sizeof(dptr->contents));

   return 0;
}


int endian_convertTypeN_reg_value_t(reg_value_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_reg_value_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_rpd_coin_t(rpd_coin_t *dptr,int dlength)
{

   /* (uint32 Ehit)	 --> (uint32|uint32)	(Ehit) */
   /* (uint32 Ghit)	 --> (uint32|uint32)	(Ghit) */

   endian_convertType1_uint32((uint32*)&dptr->Ehit,sizeof(dptr->Ehit));
   endian_convertType1_uint32((uint32*)&dptr->Ghit,sizeof(dptr->Ghit));

   return 0;
}


int endian_convertTypeN_rpd_coin_t(rpd_coin_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_rpd_coin_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_rpd_hit_t(rpd_hit_t *dptr,int dlength)
{

   /* (int32 channel)	 --> (int32|uint32)	(channel) */
   /* (float32 energy)	 --> (float32|uint32)	(energy) */
   /* (uint32 times)	 --> (uint32|uint32)	(times) */
   /* (uint32 tindex)	 --> (uint32|uint32)	(tindex) */

   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));
   endian_convertType1_uint32((uint32*)&dptr->times,sizeof(dptr->times));
   endian_convertType1_uint32((uint32*)&dptr->tindex,sizeof(dptr->tindex));

   return 0;
}


int endian_convertTypeN_rpd_hit_t(rpd_hit_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_rpd_hit_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_scaler_value_t(scaler_value_t *dptr,int dlength)
{

   /* (uint32 slot)	 --> (uint32|uint32)	(slot) */
   /* (uint32 channel)	 --> (uint32|uint32)	(channel) */
   /* (uint32 value)	 --> (uint32|uint32)	(value) */

   endian_convertType1_uint32((uint32*)&dptr->slot,sizeof(dptr->slot));
   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertType1_uint32((uint32*)&dptr->value,sizeof(dptr->value));

   return 0;
}


int endian_convertTypeN_scaler_value_t(scaler_value_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_scaler_value_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_tagger_cluster_t(tagger_cluster_t *dptr,int dlength)
{

   /* (uint32 channel)	 --> (uint32|uint32)	(channel) */
   /* (float32 energy)	 --> (float32|uint32)	(energy) */
   /* (float32 time)	 --> (float32|uint32)	(time) */
   /* (uint32 next)	 --> (uint32|uint32)	(next) */

   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));
   endian_convertType1_uint32((uint32*)&dptr->time,sizeof(dptr->time));
   endian_convertType1_uint32((uint32*)&dptr->next,sizeof(dptr->next));

   return 0;
}


int endian_convertTypeN_tagger_cluster_t(tagger_cluster_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_tagger_cluster_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_tagger_hit_t(tagger_hit_t *dptr,int dlength)
{

   /* (uint32 channel)	 --> (uint32|uint32)	(channel) */
   /* (float32 energy[2])	 --> (float32|uint32)	(energy)[2] */
   /* (uint32 times[2])	 --> (uint32|uint32)	(times)[2] */
   /* (uint32 tindex[2])	 --> (uint32|uint32)	(tindex)[2] */

   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertTypeN_uint32((uint32*)dptr->energy,2);
   endian_convertTypeN_uint32((uint32*)dptr->times,2);
   endian_convertTypeN_uint32((uint32*)dptr->tindex,2);

   return 0;
}


int endian_convertTypeN_tagger_hit_t(tagger_hit_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_tagger_hit_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_tagger_photon_t(tagger_photon_t *dptr,int dlength)
{

   /* (uint32 channel)	 --> (uint32|uint32)	(channel) */
   /* (float32 energy)	 --> (float32|uint32)	(energy) */
   /* (float32 time)	 --> (float32|uint32)	(time) */
   /* (float32 tagging_weight)	 --> (float32|uint32)	(tagging_weight) */

   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));
   endian_convertType1_uint32((uint32*)&dptr->time,sizeof(dptr->time));
   endian_convertType1_uint32((uint32*)&dptr->tagging_weight,sizeof(dptr->tagging_weight));

   return 0;
}


int endian_convertTypeN_tagger_photon_t(tagger_photon_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_tagger_photon_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_tdc_value_t(tdc_value_t *dptr,int dlength)
{

   /* (uint32 slot)	 --> (uint32|uint32)	(slot) */
   /* (uint32 channel)	 --> (uint32|uint32)	(channel) */
   /* (int32 le)	 --> (int32|uint32)	(le) */
   /* (int32 te)	 --> (int32|uint32)	(te) */

   endian_convertType1_uint32((uint32*)&dptr->slot,sizeof(dptr->slot));
   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertType1_uint32((uint32*)&dptr->le,sizeof(dptr->le));
   endian_convertType1_uint32((uint32*)&dptr->te,sizeof(dptr->te));

   return 0;
}


int endian_convertTypeN_tdc_value_t(tdc_value_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_tdc_value_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_three_photon_fit_t(three_photon_fit_t *dptr,int dlength)
{

   /* (int type)	 --> (int|uint32)	(type) */
   /* (vector3_t photon[3])	 --> (vector3_t|vector3_t)	(photon)[3] */
   /* (float chi_sq)	 --> (float|uint32)	(chi_sq) */
   /* (float penalty_func)	 --> (float|uint32)	(penalty_func) */
   /* (float constraint_func)	 --> (float|uint32)	(constraint_func) */
   /* (float beam_E)	 --> (float|uint32)	(beam_E) */
   /* (recoils_t recoil)	 --> (recoils_t|recoils_t)	(recoil) */

   endian_convertType1_uint32((uint32*)&dptr->type,sizeof(dptr->type));
   endian_convertTypeN_vector3_t((vector3_t*)dptr->photon,3);
   endian_convertType1_uint32((uint32*)&dptr->chi_sq,sizeof(dptr->chi_sq));
   endian_convertType1_uint32((uint32*)&dptr->penalty_func,sizeof(dptr->penalty_func));
   endian_convertType1_uint32((uint32*)&dptr->constraint_func,sizeof(dptr->constraint_func));
   endian_convertType1_uint32((uint32*)&dptr->beam_E,sizeof(dptr->beam_E));
   endian_convertType1_recoils_t(&dptr->recoil,sizeof(dptr->recoil));

   return 0;
}


int endian_convertTypeN_three_photon_fit_t(three_photon_fit_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_three_photon_fit_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_time_list_el_t(time_list_el_t *dptr,int dlength)
{

   /* (float32 le)	 --> (float32|uint32)	(le) */

   endian_convertType1_uint32((uint32*)&dptr->le,sizeof(dptr->le));

   return 0;
}


int endian_convertTypeN_time_list_el_t(time_list_el_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_time_list_el_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_upv_hit_t(upv_hit_t *dptr,int dlength)
{

   /* (int32 channel)	 --> (int32|uint32)	(channel) */
   /* (float32 energy)	 --> (float32|uint32)	(energy) */
   /* (uint32 times)	 --> (uint32|uint32)	(times) */
   /* (uint32 tindex)	 --> (uint32|uint32)	(tindex) */

   endian_convertType1_uint32((uint32*)&dptr->channel,sizeof(dptr->channel));
   endian_convertType1_uint32((uint32*)&dptr->energy,sizeof(dptr->energy));
   endian_convertType1_uint32((uint32*)&dptr->times,sizeof(dptr->times));
   endian_convertType1_uint32((uint32*)&dptr->tindex,sizeof(dptr->tindex));

   return 0;
}


int endian_convertTypeN_upv_hit_t(upv_hit_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_upv_hit_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_particleID_t(particleID_t *dptr,int dlength)
{

   /* (int groupID,index)	 --> (int|uint32)	(groupID) */
   /* (int groupID,index)	 --> (int|uint32)	(index) */

   endian_convertType1_uint32((uint32*)&dptr->groupID,sizeof(dptr->groupID));
   endian_convertType1_uint32((uint32*)&dptr->index,sizeof(dptr->index));

   return 0;
}


int endian_convertTypeN_particleID_t(particleID_t dptr[],int dcount)
{
   int i;

   for (i=0; i<dcount; i++)
      endian_convertType1_particleID_t(&dptr[i],sizeof(dptr[i]));

   return 0;
}


int endian_convertType1_recoils_t(recoils_t *dptr,int dlength)
{

   /* (uint32 nrecoils)	 --> (uint32|uint32)	(nrecoils) */
   /* (float32 best_t0)	 --> (float32|uint32)	(best_t0) */
   /* (recoil_t recoil[1])	 --> (recoil_t|recoil_t)	(recoil)[dptr->nrecoils] */

   endian_convertType1_uint32((uint32*)&dptr->nrecoils,sizeof(dptr->nrecoils));
   endian_convertType1_uint32((uint32*)&dptr->best_t0,sizeof(dptr->best_t0));
   endian_convertTypeN_recoil_t(dptr->recoil,dptr->nrecoils);

   return 0;
}




int endian_convertGroup(group_header_t *hdr,void *dptr,int dlength)
{
  int group=hdr->type;
  int subgroup=hdr->subtype;

  switch (group)
    {
      case GROUP_3_PHOTON_FITS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_three_photon_fits_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_3_PHOTON_FITS.\n",subgroup);
            return -1;
          }
      case GROUP_BGV_ADCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_adc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_BGV_ADCS.\n",subgroup);
            return -1;
          }
      case GROUP_BGV_CLUSTERS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_bgv_clusters_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_BGV_CLUSTERS.\n",subgroup);
            return -1;
          }
      case GROUP_BGV_COINS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_rpd_coins_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_BGV_COINS.\n",subgroup);
            return -1;
          }
      case GROUP_BGV_HITS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_bgv_hits_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_BGV_HITS.\n",subgroup);
            return -1;
          }
      case GROUP_BGV_TDCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_tdc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_BGV_TDCS.\n",subgroup);
            return -1;
          }
      case GROUP_BSD_ADCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_adc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_BSD_ADCS.\n",subgroup);
            return -1;
          }
      case GROUP_BSD_HITS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_bsd_hits_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_BSD_HITS.\n",subgroup);
            return -1;
          }
      case GROUP_BSD_PIXELS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_bsd_pixels_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_BSD_PIXELS.\n",subgroup);
            return -1;
          }
      case GROUP_BSD_TDCS_LONG:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_tdc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_BSD_TDCS_LONG.\n",subgroup);
            return -1;
          }
      case GROUP_BSD_TDCS_SHORT:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_tdc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_BSD_TDCS_SHORT.\n",subgroup);
            return -1;
          }
      case GROUP_CPV_ADCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_adc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_CPV_ADCS.\n",subgroup);
            return -1;
          }
      case GROUP_CPV_HITS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_cpv_hits_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_CPV_HITS.\n",subgroup);
            return -1;
          }
      case GROUP_CPV_TDCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_tdc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_CPV_TDCS.\n",subgroup);
            return -1;
          }
      case GROUP_DELETED:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_NOCONVERT_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_DELETED.\n",subgroup);
            return -1;
          }
      case GROUP_ESR_NPARTICLE:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_esr_nparticle_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_ESR_NPARTICLE.\n",subgroup);
            return -1;
          }
      case GROUP_ESUM_ADCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_adc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_ESUM_ADCS.\n",subgroup);
            return -1;
          }
      case GROUP_FROZEN:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_frozen_groups_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_FROZEN.\n",subgroup);
            return -1;
          }
      case GROUP_LGD_ADCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_adc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_LGD_ADCS.\n",subgroup);
            return -1;
          }
      case GROUP_LGD_CLUSTERS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_lgd_clusters_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_LGD_CLUSTERS.\n",subgroup);
            return -1;
          }
      case GROUP_LGD_CLUSTER_HITS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_lgd_hits_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_LGD_CLUSTER_HITS.\n",subgroup);
            return -1;
          }
      case GROUP_LGD_HITS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_lgd_hits_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_LGD_HITS.\n",subgroup);
            return -1;
          }
      case GROUP_LGD_RECONSTRUCT:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_lgd_reconstruct_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_LGD_RECONSTRUCT.\n",subgroup);
            return -1;
          }
      case GROUP_MAM_REGS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_reg_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_MAM_REGS.\n",subgroup);
            return -1;
          }
      case GROUP_MC_EVENT:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_mc_event_t(dptr,dlength);
          case 1:
            return endian_convertType1_mc_vertex_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_MC_EVENT.\n",subgroup);
            return -1;
          }
      case GROUP_MESONS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_mesons_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_MESONS.\n",subgroup);
            return -1;
          }
      case GROUP_PHOTONS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_photons_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_PHOTONS.\n",subgroup);
            return -1;
          }
      case GROUP_RAW:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_INTARRAY_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_RAW.\n",subgroup);
            return -1;
          }
      case GROUP_RECOIL:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_recoil_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_RECOIL.\n",subgroup);
            return -1;
          }
      case GROUP_RPD_ADCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_adc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_RPD_ADCS.\n",subgroup);
            return -1;
          }
      case GROUP_RPD_COINS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_rpd_coins_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_RPD_COINS.\n",subgroup);
            return -1;
          }
      case GROUP_RPD_HITS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_rpd_hits_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_RPD_HITS.\n",subgroup);
            return -1;
          }
      case GROUP_RPD_TDCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_tdc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_RPD_TDCS.\n",subgroup);
            return -1;
          }
      case GROUP_SCALERS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_scaler_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_SCALERS.\n",subgroup);
            return -1;
          }
      case GROUP_TAGGER_CLUSTERS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_tagger_clusters_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_TAGGER_CLUSTERS.\n",subgroup);
            return -1;
          }
      case GROUP_TAGGER_HITS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_tagger_hits_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_TAGGER_HITS.\n",subgroup);
            return -1;
          }
      case GROUP_TAGGER_PHOTONS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_tagger_photons_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_TAGGER_PHOTONS.\n",subgroup);
            return -1;
          }
      case GROUP_TAGGER_TDCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_tdc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_TAGGER_TDCS.\n",subgroup);
            return -1;
          }
      case GROUP_TIME_LIST:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_time_list_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_TIME_LIST.\n",subgroup);
            return -1;
          }
      case GROUP_UPV_ADCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_adc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_UPV_ADCS.\n",subgroup);
            return -1;
          }
      case GROUP_UPV_HITS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_upv_hits_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_UPV_HITS.\n",subgroup);
            return -1;
          }
      case GROUP_UPV_TDCS:
         switch (subgroup)
           {
          case 0:
            return endian_convertType1_tdc_values_t(dptr,dlength);
          default:
            fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Unknown subgroup %d found in group GROUP_UPV_TDCS.\n",subgroup);
            return -1;
          }
    }

  fprintf(stderr,"endianConverterAuto.c:endian_convertGroup: Error: Don't know how to convert group %d.\n",group);

  return -1;
}

/* end file */
