/*
   endianConverterAuto.h --- endian converter

   this file is automatically generated by 'endianStubGen.perl'
*/


#include <disData.h>


extern int endian_convertType1_INTARRAY_t(void*dptr,int dlength);
extern int endian_convertTypeN_INTARRAY_t(void*dptr,int dcount);
extern int endian_convertType1_NOCONVERT_t(void*dptr,int dlength);
extern int endian_convertTypeN_NOCONVERT_t(void*dptr,int dcount);
extern int endian_convertType1_double(double*dptr,int dlength);
extern int endian_convertTypeN_double(double*dptr,int dcount);
extern int endian_convertType1_uint16(uint16*dptr,int dlength);
extern int endian_convertTypeN_uint16(uint16*dptr,int dcount);
extern int endian_convertType1_uint32(uint32*dptr,int dlength);
extern int endian_convertTypeN_uint32(uint32*dptr,int dcount);
extern int endian_convertType1_uint8(uint8*dptr,int dlength);
extern int endian_convertTypeN_uint8(uint8*dptr,int dcount);
extern int endian_convertType1_vector3_t(vector3_t*dptr,int dlength);
extern int endian_convertTypeN_vector3_t(vector3_t*dptr,int dcount);
extern int endian_convertType1_vector4_t(vector4_t*dptr,int dlength);
extern int endian_convertTypeN_vector4_t(vector4_t*dptr,int dcount);


#include <itypes.h>

int endian_convertType1_adc_value_t(adc_value_t*dptr,int dlength);
int endian_convertTypeN_adc_value_t(adc_value_t dptr[],int dcount);

int endian_convertType1_adc_values_t(adc_values_t *dptr,int dlength);

#include <libBGV.h>

int endian_convertType1_bgv_cluster_t(bgv_cluster_t*dptr,int dlength);
int endian_convertTypeN_bgv_cluster_t(bgv_cluster_t dptr[],int dcount);

int endian_convertType1_bgv_clusters_t(bgv_clusters_t *dptr,int dlength);

#include <iitypes.h>

int endian_convertType1_bgv_hit_t(bgv_hit_t*dptr,int dlength);
int endian_convertTypeN_bgv_hit_t(bgv_hit_t dptr[],int dcount);

int endian_convertType1_bgv_hits_t(bgv_hits_t *dptr,int dlength);

int endian_convertType1_bsd_hit_t(bsd_hit_t*dptr,int dlength);
int endian_convertTypeN_bsd_hit_t(bsd_hit_t dptr[],int dcount);

int endian_convertType1_bsd_hits_t(bsd_hits_t *dptr,int dlength);

int endian_convertType1_bsd_pixel_t(bsd_pixel_t*dptr,int dlength);
int endian_convertTypeN_bsd_pixel_t(bsd_pixel_t dptr[],int dcount);

int endian_convertType1_bsd_pixels_t(bsd_pixels_t *dptr,int dlength);

int endian_convertType1_cpv_hit_t(cpv_hit_t*dptr,int dlength);
int endian_convertTypeN_cpv_hit_t(cpv_hit_t dptr[],int dcount);

int endian_convertType1_cpv_hits_t(cpv_hits_t *dptr,int dlength);

#include <esr.h>

int endian_convertType1_esr_particle_t(esr_particle_t*dptr,int dlength);
int endian_convertTypeN_esr_particle_t(esr_particle_t dptr[],int dcount);

int endian_convertType1_esr_nparticle_t(esr_nparticle_t *dptr,int dlength);


int endian_convertType1_frozen_groups_t(frozen_groups_t *dptr,int dlength);

#include <disData.h>


int endian_convertType1_group_header_t(group_header_t *dptr,int dlength);
int endian_convertTypeN_group_header_t(group_header_t *dptr,int dcount);


int endian_convertType1_itape_header_t(itape_header_t *dptr,int dlength);
int endian_convertTypeN_itape_header_t(itape_header_t *dptr,int dcount);

#include <lgdCluster.h>

int endian_convertType1_lgd_cluster_t(lgd_cluster_t*dptr,int dlength);
int endian_convertTypeN_lgd_cluster_t(lgd_cluster_t dptr[],int dcount);

int endian_convertType1_lgd_clusters_t(lgd_clusters_t *dptr,int dlength);

int endian_convertType1_lgd_hit_t(lgd_hit_t*dptr,int dlength);
int endian_convertTypeN_lgd_hit_t(lgd_hit_t dptr[],int dcount);

int endian_convertType1_lgd_hits_t(lgd_hits_t *dptr,int dlength);


int endian_convertType1_lgd_reconstruct_t(lgd_reconstruct_t *dptr,int dlength);

#include <mctypes.h>

int endian_convertType1_mc_particle_t(mc_particle_t*dptr,int dlength);
int endian_convertTypeN_mc_particle_t(mc_particle_t dptr[],int dcount);

int endian_convertType1_mc_event_t(mc_event_t *dptr,int dlength);


int endian_convertType1_mc_vertex_t(mc_vertex_t *dptr,int dlength);

int endian_convertType1_meson_t(meson_t*dptr,int dlength);
int endian_convertTypeN_meson_t(meson_t dptr[],int dcount);

int endian_convertType1_mesons_t(mesons_t *dptr,int dlength);

int endian_convertType1_photon_t(photon_t*dptr,int dlength);
int endian_convertTypeN_photon_t(photon_t dptr[],int dcount);

int endian_convertType1_photons_t(photons_t *dptr,int dlength);


int endian_convertType1_recoil_t(recoil_t *dptr,int dlength);
int endian_convertTypeN_recoil_t(recoil_t *dptr,int dcount);

int endian_convertType1_reg_value_t(reg_value_t*dptr,int dlength);
int endian_convertTypeN_reg_value_t(reg_value_t dptr[],int dcount);

int endian_convertType1_reg_values_t(reg_values_t *dptr,int dlength);

int endian_convertType1_rpd_coin_t(rpd_coin_t*dptr,int dlength);
int endian_convertTypeN_rpd_coin_t(rpd_coin_t dptr[],int dcount);

int endian_convertType1_rpd_coins_t(rpd_coins_t *dptr,int dlength);

int endian_convertType1_rpd_hit_t(rpd_hit_t*dptr,int dlength);
int endian_convertTypeN_rpd_hit_t(rpd_hit_t dptr[],int dcount);

int endian_convertType1_rpd_hits_t(rpd_hits_t *dptr,int dlength);

int endian_convertType1_scaler_value_t(scaler_value_t*dptr,int dlength);
int endian_convertTypeN_scaler_value_t(scaler_value_t dptr[],int dcount);

int endian_convertType1_scaler_values_t(scaler_values_t *dptr,int dlength);

int endian_convertType1_tagger_cluster_t(tagger_cluster_t*dptr,int dlength);
int endian_convertTypeN_tagger_cluster_t(tagger_cluster_t dptr[],int dcount);

int endian_convertType1_tagger_clusters_t(tagger_clusters_t *dptr,int dlength);

int endian_convertType1_tagger_hit_t(tagger_hit_t*dptr,int dlength);
int endian_convertTypeN_tagger_hit_t(tagger_hit_t dptr[],int dcount);

int endian_convertType1_tagger_hits_t(tagger_hits_t *dptr,int dlength);

int endian_convertType1_tagger_photon_t(tagger_photon_t*dptr,int dlength);
int endian_convertTypeN_tagger_photon_t(tagger_photon_t dptr[],int dcount);

int endian_convertType1_tagger_photons_t(tagger_photons_t *dptr,int dlength);

#include <tapeData.h>


int endian_convertType1_tapeHeader_t(tapeHeader_t *dptr,int dlength);
int endian_convertTypeN_tapeHeader_t(tapeHeader_t *dptr,int dcount);

int endian_convertType1_tdc_value_t(tdc_value_t*dptr,int dlength);
int endian_convertTypeN_tdc_value_t(tdc_value_t dptr[],int dcount);

int endian_convertType1_tdc_values_t(tdc_values_t *dptr,int dlength);

int endian_convertType1_three_photon_fit_t(three_photon_fit_t*dptr,int dlength);
int endian_convertTypeN_three_photon_fit_t(three_photon_fit_t dptr[],int dcount);

int endian_convertType1_three_photon_fits_t(three_photon_fits_t *dptr,int dlength);

int endian_convertType1_time_list_el_t(time_list_el_t*dptr,int dlength);
int endian_convertTypeN_time_list_el_t(time_list_el_t dptr[],int dcount);

int endian_convertType1_time_list_t(time_list_t *dptr,int dlength);

int endian_convertType1_upv_hit_t(upv_hit_t*dptr,int dlength);
int endian_convertTypeN_upv_hit_t(upv_hit_t dptr[],int dcount);

int endian_convertType1_upv_hits_t(upv_hits_t *dptr,int dlength);


int endian_convertType1_adc_value_t(adc_value_t *dptr,int dlength);
int endian_convertTypeN_adc_value_t(adc_value_t *dptr,int dcount);


int endian_convertType1_bgv_cluster_t(bgv_cluster_t *dptr,int dlength);
int endian_convertTypeN_bgv_cluster_t(bgv_cluster_t *dptr,int dcount);


int endian_convertType1_bgv_hit_t(bgv_hit_t *dptr,int dlength);
int endian_convertTypeN_bgv_hit_t(bgv_hit_t *dptr,int dcount);


int endian_convertType1_bsd_hit_t(bsd_hit_t *dptr,int dlength);
int endian_convertTypeN_bsd_hit_t(bsd_hit_t *dptr,int dcount);


int endian_convertType1_bsd_pixel_t(bsd_pixel_t *dptr,int dlength);
int endian_convertTypeN_bsd_pixel_t(bsd_pixel_t *dptr,int dcount);


int endian_convertType1_cpv_hit_t(cpv_hit_t *dptr,int dlength);
int endian_convertTypeN_cpv_hit_t(cpv_hit_t *dptr,int dcount);

int endian_convertType1_particleID_t(particleID_t*dptr,int dlength);
int endian_convertTypeN_particleID_t(particleID_t dptr[],int dcount);

int endian_convertType1_esr_particle_t(esr_particle_t *dptr,int dlength);
int endian_convertTypeN_esr_particle_t(esr_particle_t *dptr,int dcount);


int endian_convertType1_lgd_cluster_t(lgd_cluster_t *dptr,int dlength);
int endian_convertTypeN_lgd_cluster_t(lgd_cluster_t *dptr,int dcount);


int endian_convertType1_lgd_hit_t(lgd_hit_t *dptr,int dlength);
int endian_convertTypeN_lgd_hit_t(lgd_hit_t *dptr,int dcount);


int endian_convertType1_mc_particle_t(mc_particle_t *dptr,int dlength);
int endian_convertTypeN_mc_particle_t(mc_particle_t *dptr,int dcount);


int endian_convertType1_meson_t(meson_t *dptr,int dlength);
int endian_convertTypeN_meson_t(meson_t *dptr,int dcount);


int endian_convertType1_photon_t(photon_t *dptr,int dlength);
int endian_convertTypeN_photon_t(photon_t *dptr,int dcount);


int endian_convertType1_reg_value_t(reg_value_t *dptr,int dlength);
int endian_convertTypeN_reg_value_t(reg_value_t *dptr,int dcount);


int endian_convertType1_rpd_coin_t(rpd_coin_t *dptr,int dlength);
int endian_convertTypeN_rpd_coin_t(rpd_coin_t *dptr,int dcount);


int endian_convertType1_rpd_hit_t(rpd_hit_t *dptr,int dlength);
int endian_convertTypeN_rpd_hit_t(rpd_hit_t *dptr,int dcount);


int endian_convertType1_scaler_value_t(scaler_value_t *dptr,int dlength);
int endian_convertTypeN_scaler_value_t(scaler_value_t *dptr,int dcount);


int endian_convertType1_tagger_cluster_t(tagger_cluster_t *dptr,int dlength);
int endian_convertTypeN_tagger_cluster_t(tagger_cluster_t *dptr,int dcount);


int endian_convertType1_tagger_hit_t(tagger_hit_t *dptr,int dlength);
int endian_convertTypeN_tagger_hit_t(tagger_hit_t *dptr,int dcount);


int endian_convertType1_tagger_photon_t(tagger_photon_t *dptr,int dlength);
int endian_convertTypeN_tagger_photon_t(tagger_photon_t *dptr,int dcount);


int endian_convertType1_tdc_value_t(tdc_value_t *dptr,int dlength);
int endian_convertTypeN_tdc_value_t(tdc_value_t *dptr,int dcount);

int endian_convertType1_recoils_t(recoils_t*dptr,int dlength);
int endian_convertTypeN_recoils_t(recoils_t dptr[],int dcount);

int endian_convertType1_three_photon_fit_t(three_photon_fit_t *dptr,int dlength);
int endian_convertTypeN_three_photon_fit_t(three_photon_fit_t *dptr,int dcount);


int endian_convertType1_time_list_el_t(time_list_el_t *dptr,int dlength);
int endian_convertTypeN_time_list_el_t(time_list_el_t *dptr,int dcount);


int endian_convertType1_upv_hit_t(upv_hit_t *dptr,int dlength);
int endian_convertTypeN_upv_hit_t(upv_hit_t *dptr,int dcount);


int endian_convertType1_particleID_t(particleID_t *dptr,int dlength);
int endian_convertTypeN_particleID_t(particleID_t *dptr,int dcount);


int endian_convertType1_recoils_t(recoils_t *dptr,int dlength);

int endian_convertGroup(group_header_t *hdr,void *dptr,int dlength);


/* end file */
